"""Add maps_api_key to company_details

Revision ID: 419111763cbc
Revises: a3d3c5cc4efe
Create Date: 2025-09-22 16:07:10.118670

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '419111763cbc'
down_revision = 'a3d3c5cc4efe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('company_details', schema=None) as batch_op:
        batch_op.add_column(sa.Column('maps_api_key', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('company_details', schema=None) as batch_op:
        batch_op.drop_column('maps_api_key')

    # ### end Alembic commands ###
