"""Add category column to Template

Revision ID: 45716ea8e34f
Revises: 
Create Date: 2025-09-03 23:25:08.885686

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45716ea8e34f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('template', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('template', schema=None) as batch_op:
        batch_op.drop_column('category')

    # ### end Alembic commands ###
