"""Remove language_code from images table

Revision ID: 4a403418438d
Revises: 419111763cbc
Create Date: 2025-09-25 23:39:34.166123

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a403418438d'
down_revision = '419111763cbc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('images', schema=None) as batch_op:
        batch_op.drop_column('language_code')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('images', schema=None) as batch_op:
        batch_op.add_column(sa.Column('language_code', sa.VARCHAR(length=10), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
