"""Add social media fields and hours to company_details

Revision ID: a3d3c5cc4efe
Revises: bb15c02d0bf9
Create Date: 2025-09-21 23:10:16.395834

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a3d3c5cc4efe'
down_revision = 'bb15c02d0bf9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('company_details', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hours', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('linkedin_url', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('twitter_url', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('youtube_url', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('facebook_url', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('company_details', schema=None) as batch_op:
        batch_op.drop_column('facebook_url')
        batch_op.drop_column('youtube_url')
        batch_op.drop_column('twitter_url')
        batch_op.drop_column('linkedin_url')
        batch_op.drop_column('hours')

    # ### end Alembic commands ###
